version: 1.0.0.{build}
environment:
  nodejs_version: "6"
build:
  verbosity: minimal
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - npm install
build_script:
  - node node_modules\typescript\bin\tsc --rootDir ./src/ --outDir ./lib
artifacts:
- path: '\'
  name: tfso-repository
deploy:
- provider: GitHub
  auth_token:
    secure: +jk2XUVt/vMWiMD2OepSw72zo5qXtMXJYbByvNUpN53otaJhmnCbtMWVCJe70IKL
  draft: false
  force_update: false